export type {
  ElementType,
  FillStyle,
  StrokeStyle,
  EdgeStyle,
  StrokeWidth,
  BaseElement,
  RectangleElement,
  EllipseElement,
  DiamondElement,
  LineElement,
  ArrowElement,
  ArrowBinding,
  FreedrawElement,
  FreedrawPoint,
  TextElement,
  ImageElement,
  Element,
} from "./types.js";
