export type {
  ElementType,
  FillStyle,
  StrokeStyle,
  EdgeStyle,
  StrokeWidth,
  BaseElement,
  RectangleElement,
  EllipseElement,
  DiamondElement,
  LineElement,
  ArrowElement,
  FreedrawElement,
  FreedrawPoint,
  TextElement,
  Element,
} from "./types";
